### ISSUE TITLE
ValueError: Cannot feed value of shape (1, 224, 224) for Tensor 'Placeholder:0', which has shape '(?, 224, 224, 3)'

### ISSUE THREAD

**Issue by ErfolgreichCharismatisch** [kentsommer/VGG16-Image-Retrieval#3]
I get

```
Traceback (most recent call last):
  File "vgg16_example.py", line 333, in <module>
    _feature_test = sess.run(layer_test, feed_dict={vgg.imgs: [img_test]})
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 889, in run
    run_metadata_ptr)
  File "E:\Anaconda\lib\site-packages\tensorflow\python\client\session.py", line 1096, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 224, 224) for Tensor 'Placeholder:0', which has shape '(?, 224, 224, 3)'
```
with custom data in the test folder.

Solution?

**Comment by kentsommer** [comment]
@ErfolgreichCharismatisch 

That error looks like you are trying to load single channel images while the network is trained on RGB images. If that is indeed the case, the only thing you can do is retrain or use a different dataset.
